package com.web.model;

// Generated 2014-12-8 10:52:37 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * In order to avoid the waring.
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private String logonName;
	private String firstName;
	private String lastName;
	private String password;
	private Integer isAdmin;

	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}

	public User(int userId, String logonName, String firstName,
			String lastName, String password, Integer isAdmin) {
		this.userId = userId;
		this.logonName = logonName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.isAdmin = isAdmin;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getLogonName() {
		return this.logonName;
	}

	public void setLogonName(String logonName) {
		this.logonName = logonName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}

}
